### ISSUE TITLE
Create zip file or script to download all the dependencies for compiling Gazebo on Windows

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1539]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1539)) by Carlos Agüero (Bitbucket: [caguero](https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/), GitHub: [caguero](https://github.com/caguero)).**

----------------------------------------
There are a bunch of dependencies to be manually downloaded while following the instructions described in INSTALL_WIN32.md. It would be nice to automate this part.

**Comment by j-rivero** [comment]
Should be fixed in https://github.com/osrf/gazebo/issues/2901
