### ISSUE TITLE
FreeImage resize in Windows is disabled

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1586]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1586)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
See [pull request #1626](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/1626) in the `gazebo/common/Image.cc` class.

**Comment by j-rivero** [comment]
Old bug, probably fixed by the merge in the link above. Please reopen if needed.
