### ISSUE TITLE
Add heightmap support to DART by converting heightmaps to meshes.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1656]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1656)) by Aaron Gokaslan (Bitbucket: [Skylion007](https://bitbucket.org/%7Bc8f96c4f-5232-4920-9e55-b1b22db765b7%7D/)).**

----------------------------------------
DART by default does not support heightmaps, but if one just simply treats a heightmap as a mesh and exports it as such (similar to what is done with polylines), we can still use them with the physics engine.

**Comment by scpeters** [comment]
DART now supports heightmaps when using the ode or bullet collision detectors

* https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2956/page/1
* https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/3066/page/1

**Comment by trns1997** [comment]
hey @scpeters, I am hoping you can help me out with this issue. Here is my comment https://github.com/osrf/gazebo/issues/2930#issue-799433199 . As i said I am using Gazebo 11. In the code they seem to have removed ode support all together.
