### ISSUE TITLE
Nested model issues

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1718]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1718)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
[pull request #1868](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/1868) started work on nested model. 

Just some notes about what currently works for nested models and what doesn't:

- Logging: seems to record and playback correctly

- Editing: Missing nested models when loading in the editor

- Joint control panel: seems to work ok

- Model list widget: nested models don't show under parent model as they should.

- View collisions, CoM and so on: ok

- Inserting:

    - Preview doesn't load nested models .

    - Nested model doesn't show on model list at all.

    - Insert two instances of the same model - nested models don't collide with each other

- Copy / pasting: pasted nested model doesn't collide with original nested model but collides with other models.

- Align: ok

- Snap: ok

- Apply force/torque: nested model shows on the list and applying force to that doesn't work.

- Context menu: Right-clicking a nested model selects the parent model.

- Deleting: ok

- Physics engines: 

    - ODE: yes

    - bullet: yes

    - Simbody:  No
    
    - DART: (need to confirm)

**Comment by chapulina** [comment]
As mentioned on [this question](https://answers.gazebosim.org/question/25506/sdf-worldmodel-composition-across-files-is-impossible-groupingempty-containers-of-models/), the inner models of a nested model can't be manipulated.
