### ISSUE TITLE
Parse SDF frame elements and attributes

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1982]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1982)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Reference frames were added to SDF on [pull request 237](https://bitbucket.org/osrf/sdformat/pull-requests/237/support-frame-specification-in-sdf/diff), according to [this](#!/osrf/gazebo_design/src/f864f029fdd15347e6bbb4e2e46c6ce84e56a9ec/sdf_reference_geometry/sdf_reference_geometry.md?at=default&fileviewer=file-view-default) design document.

However, Gazebo is currently just ignoring `<frame>` elements and attributes.

I marked this as critical because users have been asking about this, see for example [this](http://answers.gazebosim.org/question/12752/frames-in-sdf-robot-model-how-to-define-relative-links/) question and [this](https://bitbucket.org/osrf/sdformat/issues/124/make-link-reference-frame-relative-to) issue. While this is not implemented, we should at least try to find a way to let users know whether an SDF tag is implemented.

**Comment by EricCousineau-TRI** [comment]
@scpeters @azeey Do we consider this done as of Gazebo Classic / Ignition Gazebo using `libsdformat9`?

**Comment by scpeters** [comment]
gazebo11 is now using the SemanticPose API from libsdformat9, which incorporates an aspect of the `//frame` data, which is not all the data provided by frames, but I think it's enough to close this issue.

any subsequent improvements such as rendering `//frame` elements in the 3D GLWidget, listing them in the `ModelListWidget`, or exposing them from the `Model` and `World` c++ API's should be ticketed separately.
