### ISSUE TITLE
ffmpeg 3.1 deprecation warnings on homebrew

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2002]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2002)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
ffmpeg 3.1 is now the default version in homebrew, and it has deprecated some things that are used in gazebo.

* http://build.osrfoundation.org/job/gazebo-ci-default-homebrew-amd64/103/warnings8Result/

~~~
/usr/local/Cellar/ffmpeg/3.1/include/libavformat/avformat.h:880:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
~~~

~~~
/usr/local/Cellar/ffmpeg/3.1/include/libavcodec/avcodec.h:4753:5: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
    ^


/usr/local/Cellar/ffmpeg/3.1/include/libavcodec/avcodec.h:4704:5: note: 'avcodec_decode_audio4' has been explicitly marked deprecated here
int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
    ^
~~~
We can try to depend on something old like [homebrew/versions/ffmpeg28](https://github.com/Homebrew/homebrew-versions/blob/master/ffmpeg28.rb), or we can upgrade to the new interfaces if they exist in the versions of `libavcodec` and `libavformat` used on trusty.

**Comment by traversaro** [comment]
Fixed by https://github.com/osrf/gazebo/pull/3195 .
