### ISSUE TITLE
segfault when calling ipopt virtual method

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2005]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2005)) by Anonymous.**

----------------------------------------
the following very simple plugin crashes:

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <IpIpoptApplication.hpp>
#include <gazebo/gazebo.hh>

namespace gazebo
{
    class myGazeboPlugin : public WorldPlugin
    {
    public:
        myGazeboPlugin() : WorldPlugin(), r(false)
        {
        }

        void Load(physics::WorldPtr _world, sdf::ElementPtr _sdf)
        {

            Ipopt::RegisteredOptions* a = new Ipopt::RegisteredOptions;
            a->SetRegisteringCategory("Undocumented");

        }
    };

  extern "C" GZ_COMMON_VISIBLE gazebo::WorldPlugin *RegisterPlugin();
  gazebo::WorldPlugin *RegisterPlugin()
  {
    return new myGazeboPlugin();
  }
}

note:
1. SetRegisteringCategory is a virtual method
2. by making SetRegisteringCategory a non virtual method and rebuild ipopt the segfault goes away
3. by making "a" a real object (so not a pointer) the segfault does not occur calling the method but occurs in the  Ipopt::RegisteredOptions* a = new Ipopt::RegisteredOptions; in a subsequent instantiation of the plugin object. think this happen due to the nature of the RegisterOptions itself that require to be managed through pointers.

request:
is there a way to correctly use ipopt inside a gazebo plugin?

**Comment by traversaro** [comment]
As now we have a LTS Ubuntu release (Focal 20.04) that contains a version  of Simbody that fixed this problem, I think we can finally close this  issue. Thanks to everyone that helped in solving it!

**Comment by j-rivero** [comment]
Thanks Silvio!

**Comment by traversaro** [comment]
For future reference, the issue was solved in Simbody 3.6,  so to know if a given distro is affected check the relative Simbody version: https://repology.org/project/simbody/versions .
