### ISSUE TITLE
Directional friction still broken.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2068]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2068)) by Mike Purvis (Bitbucket: [mikepurvis](https://bitbucket.org/%7B8c04da7e-73da-4d8b-ad67-4ce3ff9bf8d0%7D/)).**

The original report had attachments: [fdir1.world](https://osrf-migration.github.io/gazebo-gh-pages/data/repositories/osrf/gazebo/issues/2068/attachments/fdir1.world)

----------------------------------------
Per discussion on #463; in particular this comment:

https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/463/ode-fdir1-parameter-broken (#463)#comment-31218716

**Comment by osrf-migration** [comment]
**Original comment by Martin Pecka (Bitbucket: [peci1](https://bitbucket.org/%7B41691c43-4ae0-49ba-ba45-3c36439f5af2%7D/)).**

----------------------------------------
Anyways, there's still something rotten here even using `cone_model`.

I compared two vehicles. For the one to the left, I compute friction direction myself between collision checking and physics update. The vehicle to the right is just an omniwheel. Both are commanded the same commands - to rotate around their z axis. 

The left vehicle has no problems using either `pyramid_model` or `cone_model`.

My investigation shows, that `mu` and `mu2` are treated incorrectly in both `pyramid_model` with directional friction and `cone_model`.

# Asymmetric friction coefficients #

`mu = 2`, `mu2 = 0.5`

The vehicle to the right has the more serious problems, the more it is aligned with x axis - in both models.

Here with `pyramid_model` and `direction1` set to `[1, 0, 0]`:
https://drive.google.com/file/d/0B_WCOb_4cMD7VEZzY1B1bE4wc00/view?resourcekey=0-W_VKbTGuYukEpIrvvV4SAA

Here with `cone_model`:
https://drive.google.com/file/d/0B_WCOb_4cMD7VlQ3dEptdmljZkU/view?resourcekey=0-1NieKQPtdSbPEGpj2h63Hg

It is evident that the `cone_model` helps a lot, but it's still not perfect.

# Symmetric friction coefficients #

`mu = mu2 = 0.5`

In this case, `cone_model` works as expected, while `pyramid_model` still has issues.

Here with `pyramid_model` and `direction1` set to `[1, 0, 0]`: 
https://drive.google.com/file/d/0B_WCOb_4cMD7clNqb1RQamFUVms/view?resourcekey=0-mRN5wrhOnHDMMzAXNr1cTQ

Here with `cone_model`:
https://drive.google.com/file/d/0B_WCOb_4cMD7YXZwY3lnOGV0bW8/view?resourcekey=0-KBSM9ghWNyz9JT1MyvSTNQ

# Notes #

I looked into the `physics_friction.cc` test, but I can't easily tell what's different in this case that it works in the test and not in my experiment. The only thing is torque comes into play in my experiments. I don't set torsional friction in any way, so I'd expect it behave the same in all cases.

**Comment by AndersEllinge** [comment]
I tried to use the worlds/tracked_vehicle_wheeled.world example out of the box as explained above and can confirm the 'broken' friction over the diagonals in Gazebo 9.

However I do believe that it is actually not broken, but due to the ODE physics, as when I increase the ERP constraint of the physics solver from 0.2 to 0.6 then this weird 'broken' behavior discussed above disappears. 
If you try out  the above example without increasing the ERP, then you can visualize the contact points in the gazebo client, and you will quickly notice that at the 'broken' diagonals there are only 3-4 contact points active, meaning not all wheels are actually touching the surface! This effectively means that the ODE solver has allowed for a tiny error in the wheel joints (explanation given here http://ode.org/ode-latest-userguide.html#sec_3_7_0), which in this scenario has 'raised' the wheel joints slightly above the surface hence not actually creating any friction/collision. Reducing this error (by increasing ERP) the wheels will be in contact with the surface alot more, hence the 'broken' behavior seemingly disappears. 

The question is now rather, why does the ODE solver reach this specific solution of the joint positions slightly raised above the surface in such a repetitive fashion with a 'low' ERP constraint at the diagonals?

Please correct me if I am wrong, I just felt like sharing my discoveries as I am interested in reliably simulating a tracked vehicle.

**Comment by scpeters** [comment]
@AndersEllinge can you confirm which version of gazebo9 you are using?

**Comment by peci1** [comment]
@AndersEllinge That's an interesting hypothesis, though still not clear why would the joint lifting happen more in some directions. Could you make a short video/gif showing the behavior, so that we can comment on it?

**Comment by peci1** [comment]
And do you set ERP globally for the whole world, or did you try setting it just for the wheel joints using http://sdformat.org/spec?ver=1.6&elem=joint#ode_erp ?

**Comment by AndersEllinge** [comment]
@scpeters I am using 9.15.0

@peci1 Here is a short video https://vimeo.com/497551878. I change the global ERP from 0.2 --> 0.6 using the GUI running the worlds/tracked_vehicle_wheeled.world example. I suppose the ERP can be individually set for each wheel joint, but have not tried it out.

**Comment by peci1** [comment]
Okay, that looks pretty convincing. Could you maybe log the wheel positions to show how much do the wheels get lifted?

**Comment by AndersEllinge** [comment]
In the following screen shot I plot the Z position of the 4. and 7. right wheels pose, and the plot is started when the vehicle is 'stuck' and then starts moving to then become stuck again over a diagonal again. Just looking in general I can see lifts with a difference of up to 0.0001 using an ERP of 0.2

![Screenshot from 2021-01-06 11-37-30](https://user-images.githubusercontent.com/14728926/103759160-92a7c000-5013-11eb-8969-50734f485000.png)


This screenshot shows the Z position of the 4. right wheel using an ERP of 0.6 and no significant difference is observed.
![Screenshot from 2021-01-06 11-45-03](https://user-images.githubusercontent.com/14728926/103760110-f1ba0480-5014-11eb-8779-b69f85534c22.png)

**Comment by peci1** [comment]
Great, so this is as expected. I wouldn't start digging deeper into the linear complementarity problem formulation used in ODE to figure out why exactly this happens. If it's sufficient to raise ERP for the affected joints, this seems to be a solution.

It should, however, probably appear in some documentation. Where would be the best place(s)? Something like

> Set ERP to a higher value like 0.6 for joints connecting links which are expected to be heavily affected by friction. With low ERP values, the joint may choose to 'avoid the contact' increasing the joint error rather than make the contact and apply the friction force.

**Comment by peci1** [comment]
@osrf-migration or @scpeters or @chapulina: Could you please edit my migrated post https://github.com/osrf/gazebo/issues/2068#issuecomment-616061110 and exchange the Google drive links with the following ones? As Google has changed the public sharing link format, I now get an access request from each visitor that tries to open the files.

New links are (in the same order):
- https://drive.google.com/file/d/0B_WCOb_4cMD7VEZzY1B1bE4wc00/view?resourcekey=0-W_VKbTGuYukEpIrvvV4SAA
- https://drive.google.com/file/d/0B_WCOb_4cMD7VlQ3dEptdmljZkU/view?resourcekey=0-1NieKQPtdSbPEGpj2h63Hg
- https://drive.google.com/file/d/0B_WCOb_4cMD7clNqb1RQamFUVms/view?resourcekey=0-mRN5wrhOnHDMMzAXNr1cTQ
- https://drive.google.com/file/d/0B_WCOb_4cMD7YXZwY3lnOGV0bW8/view?resourcekey=0-KBSM9ghWNyz9JT1MyvSTNQ

Thanks!

**Comment by scpeters** [comment]
> @osrf-migration or @scpeters or @chapulina: Could you please edit my migrated post [#2068 (comment)](https://github.com/osrf/gazebo/issues/2068#issuecomment-616061110) and exchange the Google drive links with the following ones? As Google has changed the public sharing link format, I now get an access request from each visitor that tries to open the files.
> 
> New links are (in the same order):
> 
> * https://drive.google.com/file/d/0B_WCOb_4cMD7VEZzY1B1bE4wc00/view?resourcekey=0-W_VKbTGuYukEpIrvvV4SAA
> * https://drive.google.com/file/d/0B_WCOb_4cMD7VlQ3dEptdmljZkU/view?resourcekey=0-1NieKQPtdSbPEGpj2h63Hg
> * https://drive.google.com/file/d/0B_WCOb_4cMD7clNqb1RQamFUVms/view?resourcekey=0-mRN5wrhOnHDMMzAXNr1cTQ
> * https://drive.google.com/file/d/0B_WCOb_4cMD7YXZwY3lnOGV0bW8/view?resourcekey=0-KBSM9ghWNyz9JT1MyvSTNQ
> 
> Thanks!

@peci1 I just updated it
