### ISSUE TITLE
Dozens of noExplicitConstructor warnings on Xenial

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2178]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2178)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
cppcheck is currently catching 171 warnings on Xenial:

http://build.osrfoundation.org/job/gazebo-ci-pr_any-xenial-amd64-gpu-none/415/cppcheckResult/

Things like `Class 'SphericalCoordinates' has a constructor with 1 argument that is not explicit.`

**Comment by scpeters** [comment]
this was fixed in gazebo9
