### ISSUE TITLE
Gazebo configuration missing variables?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2200]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2200)) by Anonymous.**

The original report had attachments: [CMakeCache.txt](https://osrf-migration.github.io/gazebo-gh-pages/data/repositories/osrf/gazebo/issues/2200/attachments/CMakeCache.txt)

----------------------------------------
Trying to build Gazebo on VS2015.  Running the configuration in cmake-gui comes to a halt because CMake wants to know where Ogre3D and libcurl are.  But there's no path variables provided to assign paths...

**Comment by j-rivero** [comment]
Let's follow with this problems on Windows on https://github.com/osrf/gazebo/issues/2901
