### ISSUE TITLE
Windows Installer wizard for gazebo

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2252]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2252)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
There should be a single executable that installs windows for users. It should download and install everything for the user while displaying a progress bar. I think this is how windows users are used to installing stuff. 

Currently installing on windows requires downloading a bunch of dependencies and installing them in order, followed by building from source. http://gazebosim.org/tutorials?tut=install_on_windows&cat=install

**Comment by traversaro** [comment]
If anyone is still interested in this, a possible strategy to achieve once the gazebo binaries on Windows provided by conda-forge (https://github.com/conda-forge/gazebo-feedstock) are stable enough is to use [conda constructor](https://github.com/conda/constructor) or [mamba monstructor](https://github.com/mamba-org/monstructor) to generate Windows installers.

**Comment by j-rivero** [comment]
Follow in #2899
