### ISSUE TITLE
Remove spurious warnings on startup in verbose mode.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2355]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2355)) by Piyush Khandelwal (Bitbucket: [piyushk](https://bitbucket.org/%7B0aafe920-14b3-4b46-927d-421c6f4e90f2%7D/)).**

----------------------------------------
As per this thread: https://bitbucket.org/osrf/srcsim/issues/68/gpu_ray-not-supported-with-nvidia-1050, gazebo prints spurious warnings of the form:
```
[Wrn] [msgs.cc:1655] Conversion of sensor type[gpu_ray] not suppported.
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
```

The sensors work exactly as expected. Would it be possible to get rid of these warnings?

**Comment by scpeters** [comment]
we fixed the `gpu_ray` warning in #2963 but not all of them
