### ISSUE TITLE
Installation problem on Windows due to some boost libraries

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2398]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2398)) by Michele Colledanchise (Bitbucket: [miccol](https://bitbucket.org/%7B9f9eaf6c-4413-47a5-8e3a-b33130ad3132%7D/)).**

----------------------------------------
Hello, I am installing Gazebo for windows using the instructions given [here](http://gazebosim.org/tutorials?tut=install_on_windows)  

However, I am getting this error

```
#!CMake

Boost version: 1.56.0

  Boost include path: C:/Users/mcolledanchise/gz-ws/boost_1_56_0

  Could not find the following Boost libraries:

          boost_thread
          boost_signals
          boost_system
          boost_filesystem
          boost_program_options
          boost_regex
          boost_iostreams
          boost_date_time
```

I checked a bit the configure file and I saw that it is looking for the libraries in 
```
#!c++

C:\Users\mcolledanchise\gz-ws\boost_1_56_0\lib64-msvc-12.0
```

the funny thing is that I can find the dlls and libs files there. 
What could cause the problem?

Cheers
Michele

**Comment by j-rivero** [comment]
We are not planning on fixing the current installation but replacing it. Please check #2901
