### ISSUE TITLE
ModelEditor: Add menu option to open existing model

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2459]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2459)) by Simon Bøgh (Bitbucket: [sb_mtech](https://bitbucket.org/%7B48b4d695-1fa1-48ad-b9d8-17ccd0f9fb94%7D/)).**

The original report had attachments: [Gazebo_menu.png](https://osrf-migration.github.io/gazebo-gh-pages/data/repositories/osrf/gazebo/issues/2459/attachments/Gazebo_menu.png)

----------------------------------------
Add option to open an existing model from the File menu, see attached image.

**Comment by chapulina** [comment]
This is already supported, you can right-click any model and choose "Edit model" :wink:
