### ISSUE TITLE
7.13.0 debbuilds failed on trusty

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2481]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2481)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo7-debbuilder&build=465)](https://build.osrfoundation.org/job/gazebo7-debbuilder/465/) https://build.osrfoundation.org/job/gazebo7-debbuilder/465/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo7-debbuilder&build=466)](https://build.osrfoundation.org/job/gazebo7-debbuilder/466/) https://build.osrfoundation.org/job/gazebo7-debbuilder/466/

Seems to complain about linking to `copy_file` from boost filesystem:

~~~
common/libgazebo_common.so.7.13.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[3]: *** [gazebo/gzserver-7.13.0] Error 1
make[3]: Leaving directory `/var/lib/jenkins/workspace/gazebo7-debbuilder/build/gazebo-7.13.0/obj-x86_64-linux-gnu'
make[2]: *** [gazebo/CMakeFiles/gzserver.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
~~~

https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/branches/compare/gazebo7_7.13.0%0Dgazebo7_7.12.0#diff

**Comment by scpeters** [comment]
old issue for unsupported version of gazebo
