### ISSUE TITLE
Last camera's distortion affects previous cameras' distortions

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2527]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2527)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See the following world for example, where the first camera appears to have barrel distortion even though it was supposed to be pincushion. Swapping the order of models in the world makes both cameras be pincushion.

~~~
<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="default">

    <include>
      <uri>model://sun</uri>
    </include>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
              <bounce>
                <restitution_coefficient>1.0</restitution_coefficient>
                <threshold>0</threshold>
              </bounce>
              <contact>
                <ode>
                  <max_vel>10000</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
          </surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Grey</name>
            </script>
          </material>
        </visual>
      </link>
    </model>

    <model name="ball">
      <allow_auto_disable>false</allow_auto_disable>
      <pose>-1 0 1 0 0 0</pose>
      <static>false</static>
      <link name="link">
        <inertial>
          <mass>0.026</mass>
          <!-- inertia based on solid sphere 2/5 mr^2 -->
          <inertia>
            <ixx>1.664e-5</ixx>
            <iyy>1.664e-5</iyy>
            <izz>1.664e-5</izz>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyz>0</iyz>
          </inertia>
        </inertial>
        <collision name="collision">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
          <surface>
            <bounce>
              <restitution_coefficient>1.0</restitution_coefficient>
              <threshold>0</threshold>
            </bounce>
            <contact>
              <ode>
                <max_vel>10000</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
        </visual>
      </link>
    </model>

    <model name="camera_pincushion">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="pincushion">
        <sensor type="camera" name="camera_pincushion">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>0.1</k1>
              <k2>0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <model name="camera_barrel">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="barrel">
        <sensor type="camera" name="camera_barrel">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>-0.1</k1>
              <k2>-0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>-0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <include>
      <pose>-1.5 0 1 0 1.57 0</pose>
      <uri>model://checkerboard_plane</uri>
    </include>
  </world>
</sdf>
~~~

![distortion.gif](https://osrf-migration.github.io/gazebo-gh-pages/data/bitbucket.org/repo/jgXqbo/images/3100798395-distortion.gif)

**Comment by scpeters** [comment]
I can still reproduce this

**Comment by scpeters** [comment]
I am suspicious of the following lines:

https://github.com/osrf/gazebo/blob/gazebo11_11.5.1/gazebo/rendering/Distortion.cc#L197-L203

**Comment by scpeters** [comment]
I tried creating `camera_barrel` and `camera_pincushion` models, and inserting them dynamically to reproduce this problem, and I wasn't able to reproduce it; it worked fine. I'll make a branch with my test models to illustrate this.

**Comment by scpeters** [comment]
I've been able to narrow this down to a problem of initializing multiple cameras at once. I've added some example models and an example world in https://github.com/scpeters/gazebo/commit/bd789cdd8e56a62b5bdb9915b2f2b42b36561e8f.

## Loading multiple distorted cameras in a world file

This world file has models with multiple distorted cameras:

~~~
# from the root of the gazebo git repo:
$ export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$PWD/test/models
$ gazebo --verbose test/worlds/issue_2527_camera_distortion.world
~~~

### cameras_with_distortion

The world has an instance of the [cameras_with_distortion](https://github.com/scpeters/gazebo/blob/bd789cdd8e56a62b5bdb9915b2f2b42b36561e8f/test/models/cameras_with_distortion/model.sdf) model at the origin, that has barrel and pincushion cameras superimposed. Showing the images from each camera in the gazebo topic viewer shows that they have slightly different zoom / crop, but that they both have pincushion distortion:

![Screenshot from 2021-05-14 15-54-27](https://user-images.githubusercontent.com/3650755/118339094-b51f7d80-b4cc-11eb-944c-78a55615c019.png)

### camera_barrel

The world also has an instance of the [camera_barrel](https://github.com/scpeters/gazebo/blob/bd789cdd8e56a62b5bdb9915b2f2b42b36561e8f/test/models/camera_barrel/model.sdf) model at a lateral offset, but it loads with a pincushion distortion:

![Screenshot from 2021-05-14 16-00-41](https://user-images.githubusercontent.com/3650755/118339382-92da2f80-b4cd-11eb-9428-04e61b9f8609.png)

### camera_pincushion

The `camera_pincushion` model works fine.

## Spawning a distorted camera model into the scene

If you then insert a [camera_barrel](https://github.com/scpeters/gazebo/blob/bd789cdd8e56a62b5bdb9915b2f2b42b36561e8f/test/models/camera_barrel/model.sdf) model using the `Insert model` tab, its images will be properly distorted:

![Screenshot from 2021-05-14 16-11-27](https://user-images.githubusercontent.com/3650755/118339895-18121400-b4cf-11eb-8cac-00d734bbb858.png)

**Comment by scpeters** [comment]
I've looked through some of the rendering code and don't understand it, but I'm suspicious of the following code that locks and unlocks a hardware pixel buffer:

* https://github.com/osrf/gazebo/blob/gazebo11_11.5.1/gazebo/rendering/Distortion.cc#L219-L325

perhaps the lock is not doing its job?

**Comment by WilliamLewww** [comment]
It seems like the barrel camera is dependent on the pin-cushion camera. When I set the pin-cushion camera's distortion to an extreme amount, I would expect the barrel camera to stay the same, but for some reason it changes.

When I remove the `camera_pincushion` from the world, the barrel camera seems to work as expected. Even changing the values of the distortion seems to work too.

I think you were onto something with the pixel buffer and I'll be looking more into it.

![camera](https://user-images.githubusercontent.com/14305903/118573610-c0c2ac80-b737-11eb-8e45-f0899424eed3.gif)

**Comment by WilliamLewww** [comment]
When ignoring the pixel buffer and just printing out the data from the loop from the distortion, I get the following results:

camera_pincushion_distortion:
0.0766823,0.0766823,0
0.0782473,0.0766823,0
0.0790297,0.0766823,0
...

camera_barrel_distortion:
0,0,0
0,0,0
0,0,0
...

I think the locks are working, but something involving `ignition::math::Vector2d vec = this->dataPtr->distortionMap[i*this->dataPtr->distortionTexWidth+j];` may be the issue.

After writing **vec** to a file, I get the following results:

camera_pincushion_distortion:
0.0766823 0.0766823
0.0782473 0.0766823
-1 -1
...


camera_barrel_distortion:
-1 -1
-1 -1
-1 -1
...

**Comment by WilliamLewww** [comment]
I think the locks might be working properly because after **locking, writing, unlocking** and **locking, reading, unlocking,** I get the following textures:

Barrel:
<img src="https://user-images.githubusercontent.com/14305903/121746019-1762a280-caba-11eb-991f-0f9021bad004.png" width="250" height="250">

Pincushion:
<img src="https://user-images.githubusercontent.com/14305903/121746022-17fb3900-caba-11eb-9ac0-32f9e673fa10.png" width="250" height="250">

Since the textures are properly updated (from what I gathered so far), I think it might have something to do with loading the textures or passing them to the shader. Hopefully when I debug and view all the device resources I can find the issue.

**Comment by WilliamLewww** [comment]
https://github.com/osrf/gazebo/blob/a5b28cd6f67c8b37549356c8ab5b3aa17964b9f5/gazebo/rendering/Distortion.cc#L340-L344

When printing out the addresses for the `lensDistortionInstance->getTechnique()`, I noticed that they all point to the same address. Could this be the cause of the problem or should they all be pointing to the same `lensDistortionInstance->getTechnique()`?

The `lensDistortionInstance->getTechnique()`, which points to the same address for all distortion cameras, will be setting it's material to `this->dataPtr->distortionMaterial`, which is different for all distortion cameras.
```
this->dataPtr->lensDistortionInstance->getTechnique()->getOutputTargetPass()->
      getPass(0)->setMaterial(this->dataPtr->distortionMaterial);
```

camera_barrel::barrel::camera_barrel_distortionTex
lensDistortionInstance: **0x7f74ad2e4a88**
lensDistortionInstance->getTechnique(): **0x7f74ac4e16b8**
lensDistortionInstance->getTechnique()->getOutputTargetPass(): **0x7f11550b9ee8**
lensDistortionInstance->getTechnique()->getOutputTargetPass()->getPass(0): **0x7f1155a9c7a8**

camera_pincushion::pincushion::camera_pincushion_distortionTex
lensDistortionInstance: **0x7f74ad2e94c8**
lensDistortionInstance->getTechnique(): **0x7f74ac4e16b8**
lensDistortionInstance->getTechnique()->getOutputTargetPass(): **0x7f11550b9ee8**
lensDistortionInstance->getTechnique()->getOutputTargetPass()->getPass(0): **0x7f1155a9c7a8**

**Comment by iche033** [comment]
if the techniques are the same, it could mean that the material is just being overridden by whichever is set last?

If that's the case, one thing to try is see if updating the distortion texture before each render update would fix the problem. That can be done by going to `notifyMaterialRender` function, and call 

```
_material->getTechnique(0)->getPass(0)->getTextureUnitState(texName)->setTextureName(texName);
````

where `texName` would be this string:
https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/Distortion.cc#L215

**Comment by WilliamLewww** [comment]
When printing the address to `_material->getTechnique(0)->getPass(0)->getTextureUnitState(texName)` I get `nill`. When printing the number of texture unit states, I get two which makes me believe that the initial naming doesn't work.

I created a new data member `textureUnitState` so I could hold the texture unit state right when I create it:
```
this->dataPtr->textureUnitState = this->dataPtr->distortionMaterial->getTechnique(0)->getPass(0)->
      createTextureUnitState(texName);
```

I added `this->textureUnitState->setTextureName(this->textureName)` in the `notifyMaterialRender` method but it doesn't seem to be doing anything.

When setting the technique's material to the current camera material I do see the different distortions, but they are associated with the wrong camera.
```
this->lensDistortionInstance->getTechnique()->getOutputTargetPass()->getPass(0)->
      setMaterial(this->distortionMaterial);
```

![camera](https://user-images.githubusercontent.com/14305903/122803934-1d0b7580-d27c-11eb-8715-8e6625dd8ab2.gif)

I'm going to look for another workaround because I think the method runs every frame.

**Comment by scpeters** [comment]
To see that the problem doesn't happen when models are spawned dynamically, you can use `gz model --spawn-file` to spawn a model dynamically and then view the distorted camera images for that camera.

For example one can use the example world and models from https://github.com/scpeters/gazebo/commit/bd789cdd8e56a62b5bdb9915b2f2b42b36561e8f by checking out that commit or cherry-picking it.

Load the example world:

~~~
gazebo --verbose test/worlds/issue_2527_camera_distortion.world
~~~

There should be two cameras with barrel distortion and two with pincushion, but all appear to have pincushion distortion initially.

If you spawn an additional barrel camera:

~~~
gz model --spawn-file test/models/camera_barrel/model.sdf -m barrel
~~~

then view its image, and you'll see if has proper barrel distortion.

**Comment by WilliamLewww** [comment]
When I override the `notifyMaterialSetup` with:
```
virtual void notifyMaterialSetup(Ogre::uint32 _passId,
                                 Ogre::MaterialPtr& _material)
{
  printf("%s %f\n", _material->getName().c_str(), k1);
}
```

I get the following output:
```
c0/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap -0.500000
c1/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap -0.500000
c2/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap 0.500000
c3/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap 0.500000
```

When I manually add a distortion camera I get:
```
c0/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap -0.500000
c1/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap -0.500000
c2/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap 0.500000
c3/Gazebo/camera_pincushion::pincushion::camera_pincushion_CameraDistortionMap 0.500000
c4/Gazebo/camera_barrel_0::barrel::camera_barrel_CameraDistortionMap -0.500000
c5/Gazebo/camera_barrel_0::barrel::camera_barrel_CameraDistortionMap -0.500000
```

I noticed that the `notifyMaterialSetup` method is called **after** `SetCamera` is called for both cameras. This might be the issue because the `SetCamera` sets the material that is used for `notifyMaterialSetup` meaning `notifyMaterialSetup` will be using only the most recently created material.

Right now, the method order looks like:
`SetCamera(1) -> SetCamera(2) -> notifyMaterialSetup(1) -> notifyMaterialSetup(2)`
When it should be
`SetCamera(1) -> notifyMaterialSetup(1) -> SetCamera(2) -> notifyMaterialSetup(2)`

I think this is the reason cameras work when they are inserted manually:
`SetCamera(1) -> SetCamera(2) -> notifyMaterialSetup(1) -> notifyMaterialSetup(2) -> SetCamera(3) -> notifyMaterialSetup(3)`

**Comment by scpeters** [comment]
a fix was merged in #3033, but it did not include a regression test. I am re-opening this until a regression test is merged

**Comment by scpeters** [comment]
> I am re-opening this until a regression test is merged

one straightforward approach would be to replicate one of the existing camera distortion tests in [test/integration/camera_sensor.cc](https://github.com/osrf/gazebo/blob/gazebo11/test/integration/camera_sensor.cc) with cameras defined statically in the world file rather than spawned dynamically with the `SpawnCamera` API

**Comment by scpeters** [comment]
I've just discovered that the parameter leak still occurs if you specific a different background color for the scene:

~~~
    <scene>
      <background>0.0 0.0 0.0 1</background>
    </scene>
~~~

I've modified a test world in a branch as follows:

https://raw.githubusercontent.com/scpeters/gazebo/813229871fa4e7eba9ce9b79068b7ae384ea379e/test/worlds/issue_2527_camera_distortion.world

make sure that gazebo's `test/models` folder is in the `GAZEBO_MODEL_PATH` when you load the world.

**Comment by scpeters** [comment]
I've been able to reproduce this issue again when using the [IRGCameraSimSensorPlugin](https://github.com/nasa/irg_open/blob/ros2/irg_gazebo_plugins/src/IRGCameraSimPlugins/CameraSimSensorPlugin.cpp) from the `ros2` branch of `nasa/irg_open`. I'll try to create a `.repos` file and test world to simplify reproduction of this issue.

**Comment by scpeters** [comment]
there is a potential fix in https://github.com/osrf/gazebo/pull/3136
