### ISSUE TITLE
Add Gazebo Windows binaries

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2641]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2641)) by Anonymous.**

----------------------------------------
Add Gazebo Windows binaries

**Comment by traversaro** [comment]
If anyone is still interested in Gazebo binaries for Windows, we build Gazebo binaries on Windows on GitHub Actions at https://github.com/robotology/robotology-superbuild-dependencies-vcpkg, in particular as part of the `vcpkg-robotology-with-gazebo.zip` archive.

**Comment by j-rivero** [comment]
Let's follow in #2901
