### ISSUE TITLE
libgazebo9-dev unmet dependencies error (ubuntu 18.04)

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2647]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2647)) by Denzel Lee (Bitbucket: [Denzel Lee](https://bitbucket.org/%7Ba1caa58a-a8bd-49c8-9968-318444830df4%7D/)).**

----------------------------------------
Hello, I am trying to install gazebo9 on ubuntu 18.04 but I am facing some unmet dependencies errors. Initially I tried running the one-liner command `curl -sSL &lt;http://get.gazebosim.org&gt; | sh` but it threw the error,

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libgazebo9-dev : Depends: libgazebo9 (= 9.10.0-1~bionic) but it is not going to be installed
                 Depends: gazebo9-plugin-base (= 9.10.0-1~bionic)
E: Unable to correct problems, you have held broken packages.
```

So I tried to manually install the dependencies `libgazebo9` and `gazebo9-plugin-base` with `sudo apt install` and it was successful. With both `libgazebo9 (version 9.10.0-1~bionic)` and `gazebo9-plugin-base (version 9.10.0-1~bionic)` **successfully** installed, I tried to install run the one-liner command again but it is still throwing the same error that the dependencies are not met when I have installed the dependencies already.

In order to confirm whether the dependencies are met, I also ran the command `apt-rdepends -p libgazebo9-dev`, and the output shows that both `libgazebo9 (version 9.10.0-1~bionic)` and `gazebo9-plugin-base (version 9.10.0-1~bionic)`are installed.

```
Reading package lists... Done
Building dependency tree 
Reading state information... Done
libgazebo9-dev 
 Depends: freeglut3-dev [Installed]   
 Depends: gazebo9-common (= 9.10.0-1~bionic) [Installed]   
 Depends: gazebo9-plugin-base (= 9.10.0-1~bionic) [Installed]   
 Depends: libavcodec-dev [Installed]   
 Depends: libavdevice-dev [NotInstalled]   
 Depends: libavformat-dev [Installed]
 Depends: libboost-date-time-dev [Installed]
 Depends: libboost-filesystem-dev [Installed]
 Depends: libboost-iostreams-dev [Installed]
 Depends: libboost-program-options-dev [NotInstalled]
 Depends: libboost-regex-dev [Installed]
 Depends: libboost-system-dev [NotInstalled]
 Depends: libboost-thread-dev [Installed]
 Depends: libbullet-dev [NotInstalled]
 Depends: libcurl4-openssl-dev [Installed]
 Depends: libfreeimage-dev [NotInstalled]
 Depends: libgazebo9 (= 9.10.0-1~bionic) [Installed]
 :
 :
 :
```

I have also tried to manually install `libgazebo9-dev` with `sudo apt-get install` but it is also throwing the same error that the dependencies are not met. Trying on multiple devices with ubuntu 18.04 shows the same errors as well.

**Comment by j-rivero** [comment]
New arm release for gazebo9 is out. Should fix these problems.
