### ISSUE TITLE
Simulation window not scaling correctly on 4K display

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2687]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2687)) by Anonymous.**

The original report had attachments: [Screenshot_20200123_170215.png](https://osrf-migration.github.io/gazebo-gh-pages/data/repositories/osrf/gazebo/issues/2687/attachments/Screenshot_20200123_170215.png)

----------------------------------------
I installed Gazebo 9.11.0 for my Dell XPS, but the simulation window does not scale properly, as only the top-left part of the screen is rendering. I am using 4K display with 3840x2160 resolution and 2x scaling on KDE Neon. When using the 1x scaling, the window scales correctly. Is there anything that could be done without going to smaller resolution?

**Comment by bionade24** [comment]
I think this bug is the same as https://github.com/osrf/gazebo/issues/2688 and one of the issue can be closed.
