### ISSUE TITLE
protobuf 3.4.1 and zlib download links fail

### ISSUE THREAD

**Issue by ronaldpan** [osrf/gazebo#2716]
http://gazebosim.org/tutorials?tut=install_on_windows&cat=install 
protobuf 3.4.1 and zlib download links fail.
Others are OK.

**Comment by MartensCedric** [comment]
![image](https://user-images.githubusercontent.com/18620025/87080737-30057100-c1f6-11ea-869a-cf394ac03f94.png)
Seems to work fine for me! Is this still an issue for you?

**Comment by chapulina** [comment]
Thanks for checking, @MartensCedric. It also works for me. Maybe it was a temporary hiccup in the server? I'll close this for now, but @ronaldpan , feel free to reopen if the problem persists.
