### ISSUE TITLE
Accept relative paths in URIs

### ISSUE THREAD

**Issue by chapulina** [osrf/gazebo#2718]
The ability to pass relative paths in SDFormat's URIs was added on [this SDF PR](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/558) and implemented on Ignition Gazebo on [this PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/433/page/1).

It would be nice if Gazebo 11, which uses SDF9, could also support relative paths, so more SDF files can be shared between Gazebo-classic and Ignition.

**Comment by FracturedShader** [comment]
I was thinking that the easiest way would be by taking advantage of [AddFindFileCallback](https://github.com/osrf/gazebo/blob/d33e6429e3aa63181c3cef6d292370e6dc3f4320/gazebo/common/SystemPaths.hh#L126) in [InsertModelWidget](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/gui/InsertModelWidget.cc) where the call to [OnModelSelection](https://github.com/osrf/gazebo/blob/d33e6429e3aa63181c3cef6d292370e6dc3f4320/gazebo/gui/InsertModelWidget.cc#L295) would define the directory where to do additional searches (where the model.config lives) only for the duration of that model load.

Something similar could be done when loading world files, but I haven't been digging there yet.

**Comment by chapulina** [comment]
@FracturedShader , since SDFormat 8 all elements carry the [path of the file that was used to load them](http://osrf-distributions.s3.amazonaws.com/sdformat/api/9.0.0/classsdf_1_1v9_1_1Element.html#abb2a719929e71bf157368d8fb379a4ae), so we can use that to resolve the relative URIs. See #2765 . This is only possible on Gazebo 11.
