### ISSUE TITLE
ModelPtr for Plugin Inside Nested Model Does Not Reference Nested Model

### ISSUE THREAD

**Issue by blakermchale** [osrf/gazebo#2733]
Right now I have a plugin instantiated inside of a nested model. When I access the ModelPtr's name in the plugin it returns the name of the base model instead of the nested models name. I am using the `GetName()` method of the Model class. Currently, I include the model with the plugin into another model. In my case, the name returned is "swarm_carrier" instead of "realsense_camera". The sdf for the base model and included model is below.
```
<?xml version='1.0'?>
<sdf version="1.5">
  <model name="swarm_carrier">
    ...
    <include>
      <uri>model://realsense_camera</uri>
      <pose>0.13 0 0.1 0 0 0</pose>
    </include>
    ...
 </model>
</sdf>
```
```
<?xml version="1.0"?>
<sdf version="1.5">
  <model name="realsense_camera">
    <plugin name="realsense_plugin" filename="librealsense_gazebo_plugin.so"/>
    ...
  </model>
</sdf>
```
Is there a way to access the nested model's name or is there something I am doing incorrectly?

**Comment by chapulina** [comment]
I think the confusion comes from the use of the `<include>` tag. That's not creating a nested model, see the [Note on the include SDF element](http://gazebosim.org/tutorials?tut=nested_model&cat=build_robot#NoteontheincludeSDFelement). 

I'll close this but feel free to reopen if this is actually a bug.
