### ISSUE TITLE
Enable DART support in http://packages.osrfoundation.org's Gazebo11 binaries? 

### ISSUE THREAD

**Issue by traversaro** [osrf/gazebo#2752]
Hi @j-rivero, I had a small question on the Gazebo Ubuntu packages hosted on http://packages.osrfoundation.org, let me know if this is the proper place were to discuss this or if it is better to move it in https://github.com/ignition-release/gazebo11-release or somewhere else. 

There is a growing interested in using DART for iCub simulations on Gazebo11, especially for aspects related to manipulation and for providing a smooth upgrade path to Ignition Gazebo that will use DART as its default physic engine. While using DART  is relatively easy on macOS (where DART is an enabled dependency of gazebo11's homebrew bottle) or Windows (were we roll out our own binaries, so we can manage additional dependency easily), it involves a non-trivial complexity for the standard Ubuntu user, as at the moment it is necessary to compile Gazebo from source  to be able to use DART. 

As now the DART binary packages are available in http://packages.osrfoundation.org as they are a required (transitive) dependencies for `ignition-citadel`, I was wondering if it could make sense/be possible to enable DART support in Gazebo11 binaries  distributed from http://packages.osrfoundation.org ?
If that is possible at all, do you think there is something that as a community we can do to help on this? Thanks in advance! 

cc @Nicogene @xEnVrE @pattacini

**Comment by j-rivero** [comment]
> Hi @j-rivero, I had a small question on the Gazebo Ubuntu packages hosted on http://packages.osrfoundation.org, let me know if this is the proper place were to discuss this or if it is better to move it in https://github.com/ignition-release/gazebo11-release or somewhere else.

Hi Silvio! I think the issue is fine here.


> As now the DART binary packages are available in http://packages.osrfoundation.org as they are a required (transitive) dependencies for `ignition-citadel`, I was wondering if it could make sense/be possible to enable DART support in Gazebo11 binaries distributed from http://packages.osrfoundation.org ?

It has been always our intention to build Gazebo packages with all the support available so +1, I'll do some checks with the team and produce a prerelease to check that we are not going to break the ABI.

**Comment by traversaro** [comment]
> > As now the DART binary packages are available in http://packages.osrfoundation.org as they are a required (transitive) dependencies for `ignition-citadel`, I was wondering if it could make sense/be possible to enable DART support in Gazebo11 binaries distributed from http://packages.osrfoundation.org ?
> 
> It has been always our intention to build Gazebo packages with all the support available so +1, I'll do some checks with the team and produce a prerelease to check that we are not going to break the ABI.

Great, thanks a lot (I thought I had  replied to this issue but apparently I did not). If there is anything we can do to help, please let us know, thanks!

**Comment by j-rivero** [comment]
Thanks for the offer Silvio, I'm waiting for https://github.com/osrf/gazebo/pull/2770 and https://github.com/osrf/gazebo/pull/2734 to go in before doing the prerelease. Hopefully during this same week.

**Comment by traversaro** [comment]
Thanks a lot @j-rivero , the DART-enabled `.deb` are working fine, so I think we can close the issue. Just to let you know, this enabled us to easily deploy the Gazebo-based simulator of iCub for grasping, see https://github.com/robotology/icub-gazebo-grasping-sandbox if you are interested.
