### ISSUE TITLE
arch gazebo fails to install dependency ignition-math

### ISSUE THREAD

**Issue by iwishiwasaneagle** [osrf/gazebo#2763]
```
$ yay -S gazebo
...
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ignition-math
```

[yay_gazebo.log](https://github.com/osrf/gazebo/files/4825267/gazebo.log)

**Comment by j-rivero** [comment]
I'm afraid that we nothing to do with the packaging of Gazebo in Arch Linux. You might need to contact Arch maintainers about the issue.
