### ISSUE TITLE
Gazebo should print server error messages on terminal without requiring `--verbose`

### ISSUE THREAD

**Issue by ydirson** [osrf/gazebo#2805]
Sample situation: I have a gazebo instance already running, just happen to forget about it.  When I attempt to run another one, I'm left with absolutely no error message beside the `exit(255)` (yes, `exit(-1)` does not exist in real life):

```
$ gazebo -u
$ echo $?
255
$
```

The user has to dig through all logs in ~/.gazebo to find a `gzserver.log` that says `There is probably another Gazebo process running`.  It would be much more friendly to have that (and surely other server error messages) printed to stderr by default, at least when running through the `gazebo` wrapper.

**Comment by chapulina** [comment]
Maybe you're looking for the `--verbose` argument?

**Comment by chapulina** [comment]
I'm closing this, please reopen if you identify a bug on Gazebo.

**Comment by ydirson** [comment]
Well, I must say i'm surprised I have to use `--verbose` to get errors.  Years of using Linux brought the expectation to get told about errors without the need to use a flag, and with that of `--verbose` giving additional informative details about what's happening.

**Comment by ydirson** [comment]
Adjusted the issue title, but can't find the "reopen" button for some reason.

**Comment by chapulina** [comment]
> i'm surprised I have to use --verbose to get errors

See https://github.com/osrf/gazebo/issues/1705. On Ignition, we support different logging levels and default to showing errors. On Gazebo this is unlikely to change.
