### ISSUE TITLE
libcurl: (6) Could not resolve host: api.ignitionrobotics.org    ubuntu 18.04

### ISSUE THREAD

**Issue by dbdxnuliba** [osrf/gazebo#2821]
when run   gazebo in terminal 
l
ibcurl: (6) Could not resolve host: api.ignitionrobotics.org
environment:
ubunut18.04 gazebo9
![image](https://user-images.githubusercontent.com/13350158/89961470-56468280-dc74-11ea-856a-d4bd18bb9274.png)

**Comment by chapulina** [comment]
See #2607 

This issue has been fixed from later versions of Gazebo 9 onwards.

**Comment by jacob-02** [comment]
libcurl: (6) Could not resolve host: fuel.ignitionrobotics.org
I got this error when I was trying to run 
`roslaunch turtlebot3_gazebo turtlebot3_house.launch `

**Comment by elanchezhiyan-official** [comment]
try installing ignition packages,
first try after installation of ros-based ignition packages and then try installing other ignition packages,

sudo apt install ros-humble-ignition-math6-vendor 

sudo apt install ignition
sudo apt install ignition-launch-cli 
sudo apt install ignition-tools 

I hope this should work.
