### ISSUE TITLE
Blender/Collada imports look Grey'ish

### ISSUE THREAD

**Issue by HighPriest** [osrf/gazebo#2830]
Collada .dae file with baked in material renders like this:
![image](https://user-images.githubusercontent.com/58490197/90987491-a8987500-e58b-11ea-85a3-bd7d82532db0.png)
With grey ambient
But should look closer to this:
![image](https://user-images.githubusercontent.com/58490197/90987531-f7460f00-e58b-11ea-8f53-7965e096f627.png)

In blender, I've set all of the elements to use a material surface "Principled BSDF" as Gazebo doesn't allow anything else (Imports are uniformly white)

**Comment by skohlbr** [comment]
I encountered the same issue. The Blender export (using Blender > 2.80) looks like this:

>             <emission>
>               <color sid="emission">0.01 0.01 0.01 1</color>
>             </emission>
>             <diffuse>
>               <color sid="diffuse">0.64 0.6071135 0.007775764 1</color>
>             </diffuse>

What's missing is the `<ambient>` tag, which Gazebo apparently assumes to be some default value when it's missing. You can thus fix the issue by adding the tag manually in your Collada files (set the numeric value to some low/dark greyish value that works for you):

>             <ambient>
>               <color sid="ambient">0.05 0.05 0.05 1</color>
>             </ambient>

**Comment by conradstevens** [comment]
Its worth a try defining the material through a `model.material` file.
