### ISSUE TITLE
How to attach GpuRayPlugin to a sdf model

### ISSUE THREAD

**Issue by xabierolaz** [osrf/gazebo#2834]
Hi, i want to attach Gazebo's  [GpuRayPlugin] (https://github.com/osrf/gazebo/blob/6fd426b3949c4ca73fa126cde68f5cc4a59522eb/plugins/GpuRayPlugin.cc)for having a sensor that measures the distance between the model and an object.
However, I cant find any examples of how it can be implemented without using ROS

**Comment by ahcorde** [comment]
Hello @xabierolaz, 

This is not the right place to ask this kind of questions. Please use [Gazebo answers](https://answers.gazebosim.org/questions/).
