### ISSUE TITLE
SkidSteerDrivePlugin cannot find joint in model pioneer3at

### ISSUE THREAD

**Issue by QianleLi** [osrf/gazebo#2843]
I used ubuntu18.04 and gazebo 9.
Those are error messages:
[Err] [SkidSteerDrivePlugin.cc:51] Unable to find the right_front joint in model pioneer3at.
[Err] [SkidSteerDrivePlugin.cc:51] Unable to find the right_rear joint in model pioneer3at.
[Err] [SkidSteerDrivePlugin.cc:51] Unable to find the left_front joint in model pioneer3at.
[Err] [SkidSteerDrivePlugin.cc:51] Unable to find the left_rear joint in model pioneer3at.
Any idea how to fix this?
[drive_p3at.zip](https://github.com/osrf/gazebo/files/5219769/drive_p3at.zip)

**Comment by chapulina** [comment]
Hi @QianleLi , this issue tracker is for bug reports and feature requests.

It looks like you need help using a plugin, so please post a question at Gazebo Answers: https://answers.gazebosim.org/. Be sure to mention all the steps you followed to get to the error, so other people can help you. See you there!
