### ISSUE TITLE
libSimpleTrackedVehiclePlugin:can't find any topic about  ~/<vehicle name>/cmd_vel

### ISSUE THREAD

**Issue by oric97** [osrf/gazebo#2844]
Hello, I am working on a project about tracked vehicles, and then I found the ‘tracked_vehicle_simple.world’ file about tracked vehicles in gazebo-9. After I ran this example, the tracked vehicle can be controlled by the keyboard, but I did not find any ‘~/<vehicle name>/cmd_vel’ or ‘~/simple_tracked/cmd_vel_twist’ topic mentioned in the file. This is the result I got by using the ‘topic list’ command after running ‘tracked_vehicle_simple.world’ in gazebo-9:

/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/gazebo_gui/parameter_descriptions
/gazebo_gui/parameter_updates
/rosout
/rosout_agg

Here are my questions:
1. Why can't I find the topic mentioned in the file ? Is there something wrong?
2. Can the ‘libSimpleTrackedVehiclePlugin.so’ or ‘libTrackedVehiclePlugin.so’ plugin control the speed of the left and right tracks separately? If it can, how can I configure it. It would be great if there was an example.
3. Can ‘libSimpleTrackedVehiclePlugin.so’ or ‘libTrackedVehiclePlugin.so’ be used in xacro files?

I want to verify my algorithm to control the speed of the left and right tracks of my tracked vehicle separately. In order to configure the tracked vehicle in gazebo, I have made a lot of efforts, but the relevant information that can be found is too few. If there is already a plug-in in gazebo that can realize the function I want, I would be very grateful. If there is not a perfect plug-in for this function, I hope you can tell me. Looking forward to your reply.

**Comment by chapulina** [comment]
> Why can't I find the topic mentioned in the file ? Is there something wrong?

It looks like you're looking for ROS topics, but this plugin doesn't use ROS.

---

This issue tracker is for bug reports. Please post technical questions like these at https://answers.gazebosim.org/. I'll close this issue now, see you at Gazebo Answers!
