### ISSUE TITLE
unable to install gazebo9_9.15 on ubuntu 18 ,64bit PC

### ISSUE THREAD

**Issue by AbelDengGang** [osrf/gazebo#2855]
I update source from [http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install](http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install), but it report error when I try to install it:
`gang@gang-Ubuntu:~$ sudo apt install gazebo9 gazebo9-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gazebo9 : Depends: gazebo9-common (= 9.15.0-1~bionic) but 9.15.0-2~bionic is to be installed
           Recommends: gazebo9-plugin-base
E: Unable to correct problems, you have held broken packages.
`

From the [http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo9/](http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo9/) , I can find gazebo9_9.15.0-2~bionic_**arm64**.deb  and gazebo9-common_9.15.0-2~bionic_all.deb . Is gazebo9_9.15.0-2~bionic_**amd64**.deb missed for ubuntu 18?

**Comment by deadln** [comment]
I have the same problem:

$ sudo apt install gazebo9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gazebo9 : Depends: gazebo9-common (= 9.15.0-1~bionic) but 9.15.0-2~bionic is to be installed
           Recommends: gazebo9-plugin-base
E: Unable to correct problems, you have held broken packages.

 I succeed to install gazebo9-common(9.15.0-2) manually, but it looks like that there is 9.15.0-1 version is supposed to be. I tried this:

$ sudo apt install gazebo9-common=9.15.0-1~bionic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '9.15.0-1~bionic' for 'gazebo9-common' was not found

And there is no clue how to install this older version in entire Internet. And the same problem with gazebo9-plugin-base, but it depend on gazebo9:

$ sudo apt install gazebo9-plugin-base
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gazebo9-plugin-base : Depends: gazebo9 (= 9.15.0-1~bionic)
E: Unable to correct problems, you have held broken packages.

I think this error could be related to recent update of gazebo v9.15

**Comment by GitSRealpe** [comment]
same here, just a week ago it was installing without any problems with the same apt command
```
sudo apt-get install ros-kinetic-gazebo9-*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'ros-kinetic-gazebo9-dev' for glob 'ros-kinetic-gazebo9-*'
Note, selecting 'ros-kinetic-gazebo9-msgs' for glob 'ros-kinetic-gazebo9-*'
Note, selecting 'ros-kinetic-gazebo9-ros' for glob 'ros-kinetic-gazebo9-*'
Note, selecting 'ros-kinetic-gazebo9-plugins' for glob 'ros-kinetic-gazebo9-*'
Note, selecting 'ros-kinetic-gazebo9-ros-control' for glob 'ros-kinetic-gazebo9-*'
Note, selecting 'ros-kinetic-gazebo9-ros-pkgs' for glob 'ros-kinetic-gazebo9-*'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-kinetic-gazebo9-dev : Depends: libgazebo9-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by traversaro** [comment]
Example of this failure in CI: https://github.com/robotology/gazebo-yarp-plugins/runs/1207011683 .

**Comment by v-lopez** [comment]
Same. 

It looks like gazebo9 version `9.15.0-2~bionic`is missing from here, only `9.15.0-1~bionic` is available http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo9/

Happening since last Friday.

**Comment by gavanderhoorn** [comment]
I believe I've ran into the same problem, but on `16.04` (#2744).

Same version, just for `~xenial`.

**Comment by j-rivero** [comment]
My bad sorry. release the update version on Bionic should fix the problem with this version:  [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo9-debbuilder&build=650)](https://build.osrfoundation.org/job/gazebo9-debbuilder/650/)

Let's relax the dependency on the common package and we will update it if we need users to update it by some reason in the future. This should avoid the problem in the future: ignition-release/gazebo9-release#9

**Comment by j-rivero** [comment]
Testing installation job for Xenial/amd64 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-gazebo9_pkg-bionic-amd64&build=1)](https://build.osrfoundation.org/job/gazebo-install-gazebo9_pkg-bionic-amd64/1/). Please reopen if needed.

**Comment by gavanderhoorn** [comment]
@j-rivero: I'm not up-to-date on the syncing policy for Gazebo. Will these builds be available immediately? Or after a specific sync?

---

Edit:

> Testing installation job for Xenial/amd64 [![Build Status](https://camo.githubusercontent.com/5e0529f1cb4d87942e4cecc4880f793b075e04a7/68747470733a2f2f6275696c642e6f7372666f756e646174696f6e2e6f72672f6275696c645374617475732f69636f6e3f6a6f623d67617a65626f2d696e7374616c6c2d67617a65626f395f706b672d62696f6e69632d616d643634266275696c643d31)](https://build.osrfoundation.org/job/gazebo-install-gazebo9_pkg-bionic-amd64/1/). Please reopen if needed.

This links to a Bionic build (ie: `gazebo-install-gazebo9_pkg-bionic-amd64`)?

**Comment by j-rivero** [comment]
> @j-rivero: I'm not up-to-date on the syncing policy for Gazebo. Will these builds be available immediately? Or after a specific sync?

When releasing directly to stable, they are, yes. There are no sync procedures in Gazebo repositories (yet).





> This links to a Bionic build (ie: `gazebo-install-gazebo9_pkg-bionic-amd64`)?

sorry, [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-gazebo9_pkg-xenial-amd64)](https://build.osrfoundation.org/job/gazebo-install-gazebo9_pkg-xenial-amd64/)
