### ISSUE TITLE
ubuntu 20.04 gazebo 11.0.0 Unregistered physics engine [dart]

### ISSUE THREAD

**Issue by ycpss91255** [osrf/gazebo#2872]
surroundings:
  * osrf/ros:noetic-desktop-full
  * gazebo 11.0.0

error code:
  [Err] [Server.cc:442] Unregistered physics engine [dart], the default will be used instead.

I use osrf/ros:noetic-desktop-full without dart physics engine when executing gazebo
![error2](https://user-images.githubusercontent.com/54975526/98369578-2856bb80-2074-11eb-80a5-7da1b07903cb.png)

**Comment by chapulina** [comment]
Could you try updating your installation? I believe DART support is shipped with Gazebo since version 11.1.0, see https://github.com/osrf/gazebo/issues/2752.

**Comment by ycpss91255** [comment]
Ok, Let me try.

**Comment by ycpss91255** [comment]
Hi! I succeeded. I use orsf/ros-noetic-desktop-focal and sudo apt-get install gazebo 11, but I want to ask if this bug will be fixed?

**Comment by chapulina** [comment]
I'm glad to hear it worked. It looks like there isn't a bug, the issue has been addressed in a newer version, so I'm closing this issue.

**Comment by ycpss91255** [comment]
I found that simply sudo apt-get install gazebo11 can also solve the problem
