### ISSUE TITLE
Support for floating point pixel formats is incomplete

### ISSUE THREAD

**Issue by scpeters** [osrf/gazebo#2919]
The `rendering::Camera::OgrePixelFormat` function has logic for supporting [`"FLOAT32"` and `"FLOAT16"` pixel format strings](https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/gazebo/rendering/Camera.cc#L1003-L1006), but these format strings are not supported by [rendering::Camera::ImageDepth](https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/gazebo/rendering/Camera.cc#L917-L942).

**Comment by iche033** [comment]
pull request #2918

**Comment by scpeters** [comment]
fixed by #2918
