### ISSUE TITLE
Import ignition modules in python 2.7

### ISSUE THREAD

**Issue by NishanthARao** [osrf/gazebo#2931]
Hi all.

I am trying to import ignition modules like transport and msgs on python2.7 .
I have installed ```libignition-transport4-dev``` and ```ibingition-msgs-dev```. But when I do `import ignition` i get an import error saying `No module named ignition`. Can someone please help me with this? Thank you

**Comment by trns1997** [comment]
I am not sure it is as simple as that. Check out the following:  https://github.com/robotology/gym-ignition 
Not sure if this is what you want. But hopefully it is.

**Comment by NishanthARao** [comment]
@trns1997 Thanks for your reply. Unfortunately, I too stumbled upon this earlier, and it is not what I want. Basically I want to plot visual markers on Gazebo like they did [here](https://www.youtube.com/watch?v=egWAMbU7f6Y) from python script directly. I guess that's not possible now?

**Comment by trns1997** [comment]
The only way i see this possible is by writing your own gazebo plugin using C++, that spawns markers in the world. Other than that I am not sure how you could do this using python unless you find a python wrapper for gazebo. Sorry I can't be of more help.

**Comment by NishanthARao** [comment]
@trns1997 Yeah, currently I think that's the only way to do it. Anyways, thank you for the suggestions.

**Comment by chapulina** [comment]
Gazebo only provides C++ APIs. There are external projects like gym-ignition that provide python bindings to Ignition libraries, so I recommend you look into those.
