### ISSUE TITLE
Potentially incorrect gearbox simulation in Gazebo 9

### ISSUE THREAD

**Issue by vmanoj1996** [osrf/gazebo#2942]
I have a gearbox joint setup between two gear links and a gear base link. Gearbox joint constrains the motion between first and second gear as expected. However when gear's base is rotated by applying torque, the gears do not turn as expected. It seems like the gearbox joint is working relative to global frame instead of gear's base.

[SDF snippet](https://gist.github.com/vmanoj1996/577a27bd16aa2ffa3e4db957bd112306)

Shared a [video for reference](https://www.youtube.com/watch?v=2AMS1-87unc)

Hoping to get more clarity on this issue. Thanks in advance!

**Comment by Maxx84** [comment]
FYI, I was not able to reproduce your issue on Gazebo 11.
See [video](https://youtu.be/GXarabos-ZY).

**Comment by Maxx84** [comment]
Same with 9.16.0.

**Comment by vmanoj1996** [comment]
Thanks for checking @Maxx84. I was facing the issue in Gazebo 9.0.0 earlier. It does not happen on Gazebo 9.17. Closing this issue.
