### ISSUE TITLE
Parsing altimeter sensors from SDF 1.7

### ISSUE THREAD

**Issue by Teusner** [osrf/gazebo#2956]
Hi,

I use Gazebo 11 and it seems that I can use SDF up to version 1.7. There is an altimeter sensor in SDF 1.7 (even since SDF 1.5), but it seems to don't be parsed by Gazebo-11 : [Link to the Gazebo sensor parsing file](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/msgs/msgs.cc#L1785-L1847)

Is this a `TODO` because altimeters are not implemented in the Gazebo engine so you don't parse it or an omission ?

Best Regards

**Comment by scpeters** [comment]
the `msgs::SensorFromSDF` code is used mainly for sending information about the current models and sensors over gazebo transport so it can be displayed in `gzclient`. The altimeter is loaded fine in `gzserver`; try the following test world for example:

* https://github.com/osrf/gazebo/blob/67c43463c87685b7c9d485a9f8d2e6ac760815b9/test/worlds/test_altimeter_linear_angular.world
