### ISSUE TITLE
.

### ISSUE THREAD

**Issue by newcanopies** [osrf/gazebo#2987]

**Comment by j-rivero** [comment]
I think that the issue belongs more to the repo https://github.com/ros-simulation/gazebo_ros_pkgs than to Gazebo itself. Not sure if they can help you but, did you read the [migration notes on spawn/delete for ROS2](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Spawn-and-delete)?

If that does not help you at all, please open an issue in the `gazebo_ros_pkgs` repository.
Thanks!

**Comment by newcanopies** [comment]
thanks @j-rivero, I read/tested ALL the available documentation including [ migration notes on spawn/delete for ROS2](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Spawn-and-delete), but **none of the available methods** load a URDF with visual meshes!

**Comment by newcanopies** [comment]
https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1236

**Comment by newcanopies** [comment]
Same issue:
https://answers.gazebosim.org/question/26073/cannot-spawn-urdf-into-gazebo-using-ros2/

> In my URDF I have built my robot using meshes, and I suspect that when passing the xml data to spawn_entity on a topic, the location or file in formation of those meshes are not completed transferred. I suspect this to be the case, because if I build a robot with out meshes and use basic geometries ( box, cylinder..) in the urdf, then everything works fine and I am able to spawn the robot from a urdf into gazebo using ros2.
