### ISSUE TITLE
Issue with libgazebo11 install in ubuntu 20.04

### ISSUE THREAD

**Issue by MathisFrankB** [osrf/gazebo#2995]
Attempting to apt install gazebo11 on a newly installed 20.04 machine is failing due to conflicts in libgazebo11. Attempting to install libgazebo11 gives the following result:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgazebo11 : Depends: libignition-common3 (>= 3.12.0) but 3.11.1-1~focal is to be installed
               Depends: libignition-math6 (>= 6.8.0) but 6.7.0-1~focal is to be installed
E: Unable to correct problems, you have held broken packages.

For more information:
(results from lsb_release -a: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
)

the results for "apt show libgazebo11" is:
Package: libgazebo11
Version: 11.5.0-1~focal
Priority: extra
Section: libs
Source: gazebo11
Maintainer: Nate Koenig <nate@osrfoundation.org>
Installed-Size: 29.0 MB
Depends: libassimp5 (>= 5.0.1~ds0), libavcodec58 (>= 7:4.2), libavdevice58 (>= 7:4.0), libavformat58 (>= 7:4.2), libavutil56 (>= 7:4.0), libboost-filesystem1.71.0, libboost-iostreams1.71.0, libboost-program-options1.71.0, libboost-regex1.71.0-icu66, libboost-thread1.71.0, libbullet2.88 (>= 2.88+dfsg), libc6 (>= 2.29), libccd2, libcurl4 (>= 7.16.2), libdart6 (>= 6.9.2), libdart6-collision-bullet (>= 6.9.2), libfreeimage3, libgcc-s1 (>= 3.0), libgdal26 (>= 3.0.0), libgl1, libglib2.0-0 (>= 2.12.0), libgts-0.7-5 (>= 0.7.6), libignition-common3 (>= 3.12.0), libignition-fuel-tools4 (>= 4.3.0), libignition-math6 (>= 6.8.0), libignition-msgs5 (>= 5.7.0), libignition-transport8 (>= 8.2.0), libode8, libogre-1.9.0v5 (>= 1.9.0+dfsg1-9~), libprotobuf17, libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.8.0) | libqt5gui5-gles (>= 5.8.0), libqt5widgets5 (>= 5.12.2), libqwt-qt5-6 (>= 6.1.2), libsdformat9 (>= 9.5.0), libsimbody3.6, libspnav0 (>= 0.2.2), libstdc++6 (>= 9), libswscale5 (>= 7:4.0), libtar0, libtbb2 (>= 2017~U7), libtinyxml2-6a (>= 6.0.0), libtinyxml2.6.2v5, libx11-6
Conflicts: libgazebo10, libgazebo5, libgazebo6, libgazebo7, libgazebo8, libgazebo9
Homepage: http://gazebosim.org
Download-Size: 8,861 kB
APT-Sources: http://packages.ros.org/ros/ubuntu focal/main amd64 Packages
Description: Open Source Robotics Simulator - shared library
 Gazebo is a multi-robot simulator for outdoor environments. Like
 Stage (part of the Player project), it is capable of simulating a
 population of robots, sensors and objects, but does so in a
 three-dimensional world. It generates both realistic sensor feedback
 and physically plausible interactions between objects (it includes an
 accurate simulation of rigid-body physics).
 .
 This package gathers shared libraries used

**Comment by StefanFabian** [comment]
It seems like the libgazebo11 package was built against a newer version of the libignition packages than is available in the repositories.

**Comment by Timple** [comment]
Minimal Dockerfile to reproduce:
```Dockerfile
FROM ros:noetic-robot
RUN apt-get update -qq && apt-get install -y libgazebo11
```

output:
```bash
Step 2/2 : RUN apt-get update -qq && apt-get install -y libgazebo11
 ---> Running in 7fd6083d3d3e
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgazebo11 : Depends: libignition-common3 (>= 3.12.0) but 3.11.1-1~focal is to be installed
               Depends: libignition-math6 (>= 6.8.0) but 6.7.0-1~focal is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -qq && apt-get install -y libgazebo11' returned a non-zero code: 100
```

**Comment by j-rivero** [comment]
A bug introduced in https://github.com/ros-infrastructure/reprepro-updater/pull/111 that missed the update of `gazebo11-plugin-base`. As a workaround, using the `packages.osrfoundation.org` repository should solve the problem:

From [install instructions](http://gazebosim.org/tutorials?tut=install_ubuntu):
```
curl -sSL http://get.gazebosim.org | sh
```
or
```
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
sudo apt-get update
```
Sorry for the inconvenience.

**Comment by nlamprian** [comment]
When can we expect the fix in the official ubuntu repo?

**Comment by j-rivero** [comment]
> When can we expect the fix in the official ubuntu repo?

Hopefully today, hopefully in about 6-7 hours.

**Comment by j-rivero** [comment]
I see the test case working now, credit goes to the great @nuclearsandwich . Please reopen if you still have failures.
