### ISSUE TITLE
How to install gazebo 9.16?

### ISSUE THREAD

**Issue by wanguangxi** [osrf/gazebo#3011]
Hi,

Now, we install gazebo9, the default version in 9.18. I have to install gazebo 9.16 due to some reason, So how to install it?

thank you!

**Comment by j-rivero** [comment]
Hello:

If I understand it correctly, you are looking for previous gazebo binaries corresponding to version 9.16. All the debs are available in this page http://gazebosim.org/distributions/gazebo/releases/ you will need to download them manually and install them using dpkg.

Please next time use answers.gazebosim.org for these kind of questions. The issue tracker is more oriented to reporting bugs or failures. Thanks.
