### ISSUE TITLE
[QUESTION] [NEWBIE] Why use revolute joint over continuous joint?

### ISSUE THREAD

**Issue by peneroka** [osrf/gazebo#3012]
Hello, I'm a newbie and coming here from the [tutorial of adding velodyne sensor](http://gazebosim.org/tutorials?cat=guided_i&tut=guided_i1) . In the tutorial, it shows the use of `revolute` joint with big max and min limit (`10000000000000000` radian and `-10000000000000000` radian). Though, in the documentation of SDF [here](http://sdformat.org/spec?ver=1.6&elem=joint#joint_type), it shows that there is a joint type called `continuous` which I think is more suitable for the movement of rotation with no limited angle. Is there any reason of why in this tutorial use `revolute` joint instead of `continuous` joint? Thanks.

P.S. : Is it proper to ask this kind of question as a GitHub issue? Or is there a forum dedicated to ask this kind of question? (StackOverflow, or something?)

**Comment by j-rivero** [comment]
> P.S. : Is it proper to ask this kind of question as a GitHub issue? Or is there a forum dedicated to ask this kind of question? (StackOverflow, or something?)

There is one, indeed: answers.gazebosim.org/ let's follow there. Thanks.
