### ISSUE TITLE
Transfer libgazebo9-dev dependency from Ubuntu to Windows

### ISSUE THREAD

**Issue by nikitabeebe** [osrf/gazebo#3026]
I'm trying to run AirSim and Unreal Engine on my windows laptop, but the package requires libgazebo9-dev, which is only supported on Ubuntu versions. Can I download libgazebo9-dev on Ubuntu and then transfer those files to the windows side? (Running virtual box with Ubuntu)

Otherwise, how can I obtain the lib dependency on my windows in order to run the other simulations and packages?

**Comment by chapulina** [comment]
See https://github.com/osrf/gazebo/issues/2901 for the current situation regarding Gazebo on Windows.
