### ISSUE TITLE
Visual plugin not getting loaded on server side

### ISSUE THREAD

**Issue by winwinashwin** [osrf/gazebo#3029]
I have a world file in which I attach a visual plugin to the ground plane. However after launching the world in gazebo the visual plugin is only being loaded on the client side and not on the server side. But as soon as I spawn a robot the plugin gets loaded on the server side. Is this an expected behaviour and if so is there any way I can force the plugin to be loaded on the server side before spawning the bot?

**Comment by iche033** [comment]
that's expected. The server side does not start the rendering system if there are no rendering sensors, e.g. camera, depth camera, etc) in the world to avoid any unnecessary computations. So in your case, the robot probably has a rendering sensor, which causes rendering to start on the server side and the visual plugin to load server side. One hacky workaround is to launch the world with a ground plane and a camera model to force the visual plugin to be loaded on the server side.
