### ISSUE TITLE
run gazebo error

### ISSUE THREAD

**Issue by chongjeelee** [osrf/gazebo#3130]
when i input 'gazebo' in terminal,it ocurred this.
![image](https://user-images.githubusercontent.com/30140969/140882723-2fafc4c6-6353-4684-ab4e-cd65d9702265.png)
who can i solve this problem?thanks.

**Comment by traversaro** [comment]
Hi @chongjeelee, you can probably get more information (and provide it in the issue) by running `gazebo --verbose` .

**Comment by chongjeelee** [comment]
> Hi @chongjeelee, you can probably get more information (and provide it in the issue) by running `gazebo --verbose` .

![image](https://user-images.githubusercontent.com/30140969/140895045-a8858e25-76de-4f61-9b49-4100d09a7b3c.png)
ok,i can start gazebo,but i find a new problem...
![image](https://user-images.githubusercontent.com/30140969/140895393-75decbfd-781f-47d2-8362-ba226c2bb0f9.png)
i can not get the topics from gazebo in terminal (rostopic list)

**Comment by traversaro** [comment]
Even in this case, if you could run `gazebo --verbose` you will get more information that will be helpful for you and for anyone else to debug the problem. However, if this is not a specific bug of Gazebo but rather a specific problem of your setup, you can consider posting in https://answers.gazebosim.org/questions/ instead.

**Comment by winwinashwin** [comment]
@chongjeelee 

Running `gazebo` directly from the terminal won't work with ROS. You'll need to launch gazebo using the ROS Interface, ie 
[`gazebo_ros_pkgs`](https://github.com/ros-simulation/gazebo_ros_pkgs).

To make it more maintainable, you can write a launch file dedicated to launching gazebo with your desired flags.
Here is a sample template

```xml
<launch>
    <include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="world_name" value="$(find your-pkg-with-worlds)/worlds/your-world-file-name.world"/>
        <arg name="paused" value="true"/>   <!-- Starts gazebo with physics paused -->
        <arg name="use_sim_time" value="true"/>
        <arg name="gui" value="true"/>
        <arg name="headless" value="false"/>
        <arg name="debug" value="false"/>
        <arg name="verbose" value="true"/>
    </include>
</launch>
```

The arguments are all self explanatory. If you need further info you can consult `gazebo_ros_pkgs` documentation.

**Comment by chongjeelee** [comment]
> @chongjeelee
> 
> Running `gazebo` directly from the terminal won't work with ROS. You'll need to launch gazebo using the ROS Interface, ie [`gazebo_ros_pkgs`](https://github.com/ros-simulation/gazebo_ros_pkgs).
> 
> To make it more maintainable, you can write a launch file dedicated to launching gazebo with your desired flags. Here is a sample template
> 
> ```
> <launch>
>     <include file="$(find gazebo_ros)/launch/empty_world.launch">
>         <arg name="world_name" value="$(find your-pkg-with-worlds)/worlds/your-world-file-name.world"/>
>         <arg name="paused" value="true"/>   
>         <arg name="use_sim_time" value="true"/>
>         <arg name="gui" value="true"/>
>         <arg name="headless" value="false"/>
>         <arg name="debug" value="false"/>
>         <arg name="verbose" value="true"/>
>     </include>
> </launch>
> ```
> 
> The arguments are all self explanatory. If you need further info you can consult `gazebo_ros_pkgs` documentation.

good! it does work,thank you so much!
