### ISSUE TITLE
Gazebo highly cpu intensive in multi-robot simulations

### ISSUE THREAD

**Issue by winwinashwin** [osrf/gazebo#3131]
I am using Gazebo 11 with ROS Noetic and is trying to simulate multi-robot navigation using 4-5 turtlebot3 robots. Gazebo seems to be really cpu intensive and the `Realtime Factor` of the simulation drastically goes down. Is this an expected behavior? Is there any configuration changes or ODE settings I can tweak to make it less CPU intensive?

**Comment by chapulina** [comment]
Hi @nocoinman , please ask this kind of question at https://answers.gazebosim.org. This issue tracker is for bug reports and feature requests.

Simulation performance is highly dependent on your hardware. Some high-level recommendations:

* Remove all the sensors that you don't need, or reduce their resolution and update rate
* Increase the time step a bit, but be careful not to make the simulation unstable
