### ISSUE TITLE
Starting gazebo in windows batch mode

### ISSUE THREAD

**Issue by cogneos** [osrf/gazebo#3204]
Help needed in creating a batch file that launches gazebo environment, namely
1. Start the anaconda prompt
2. Activate gazebo environment
3. Launch gazebo
I'm able to accomplish (1.)  only, by copying shell launch command <%windir%\System32\cmd.exe "/K" C:\Users\gorokhov\Programs\MiniConda\Scripts\activate.bat C:\Users\gorokhov\Programs\MiniConda>
Anyone knows the full sequence?

**Comment by traversaro** [comment]
Hi @cogneos, not sure if you are still looking into this, anyhow you can skip `1.` and directly activate the environment in which `gazebo` is installed (let's imagine it is called `gzenv`), and then you can also call gazebo in the same command by chaining the commands with `&&`, see:
~~~
cmd.exe /k C:\Users\gorokhov\Programs\MiniConda\Scripts\activate.bat gzenv && gazebo
~~~
