### ISSUE TITLE
Gazebo 11 on ubuntu 22.04 arm

### ISSUE THREAD

**Issue by Fricodelco** [osrf/gazebo#3263]
I tried to install gazebo11 via apt on ubuntu 22.04 arm64 build and figure out that there is no deb packages for arm architecture.
Also i tried to build from source and got issues with the libsdformat9 library.
Can you help me with this?

**Comment by traversaro** [comment]
We already have an issue tracking this problem in https://github.com/osrf/gazebo/issues/3236, do you think we can close this as a duplicate?

**Comment by Fricodelco** [comment]
yes, thank you
