### ISSUE TITLE
Windows Jenkins build failures related to jom

### ISSUE THREAD

**Issue by scpeters** [osrf/gazebo#3327]
## Environment
* OS Version: whichever version is used by [win-ec2.nv.WinS22-1e4911eb](https://build.osrfoundation.org/computer/win-ec2.nv.WinS22-1e4911eb/)
* Source or binary build? source build of eb8102865ac513d7ce6f219734380788e4880ae4 as part of https://github.com/gazebosim/gazebo-classic/pull/3325

## Description
* Expected behavior: it should attempt to compile gazebo
* Actual behavior: it fails with a `jom` error just after configuring with cmake

~~~
# BEGIN SECTION: compiling gazebo
        1 file(s) copied.

jom 1.1.3 - empower your cores

Error: syntax error in C:\J\workspace\gazebo-ci-pr_any-windows7-amd64\ws\gazebo-classic\build\deps\opende\OPCODE\CMakeFiles\gazebo_opcode.dir\build.make line 76
Error: Target deps\opende\ou\CMakeFiles\gazebo_opende_ou.dir\depend doesn't exist.
jom: C:\J\workspace\gazebo-ci-pr_any-windows7-amd64\ws\gazebo-classic\build\CMakeFiles\Makefile2 [deps\opende\OPCODE\CMakeFiles\gazebo_opcode.dir\all] Error 2
~~~

The last successful build was on April 15th:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/3694/

The first failing build in the history was on April 18th:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/3695/

## Steps to reproduce

1. Run https://build.osrfoundation.org/job/gazebo-ci-gazebo11-windows7-amd64
2.
3.

**Comment by roncapat** [comment]
#3309 also affected

**Comment by j-rivero** [comment]
The Windows CI support in Jenkins has been removed. Close the issue as a side effect of this.
