### ISSUE TITLE
Gazebo fails to compile against graphviz 10.0

### ISSUE THREAD

**Issue by scpeters** [osrf/gazebo#3372]
## Environment
* OS Version: macOS 
* Source or binary build? source build of 11.14.0

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=3068)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/3068/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/3068/

## Description
* Expected behavior: it should compile successfully with graphviz
* Actual behavior: it fails to compile

## Steps to reproduce

1. `brew install gazebo11`
2.
3.

## Output

The log in that CI job linked above does not include the relevant error, but I found the following when reproducing locally:

~~~
/tmp/gazebo11-20240220-52120-92epuq/gazebo-11.14.0/gazebo/gui/qgv/QGVSubGraph.cpp:47:53: error: use of undeclared identifier 'TRUE'
    Agnode_t *node = agnode(_sgraph->graph(), NULL, TRUE);
                                                    ^
/tmp/gazebo11-20240220-52120-92epuq/gazebo-11.14.0/gazebo/gui/qgv/QGVSubGraph.cpp:53:39: error: use of undeclared identifier 'TRUE'
    agsubnode(_sgraph->graph(), node, TRUE);
                                      ^
/tmp/gazebo11-20240220-52120-92epuq/gazebo-11.14.0/gazebo/gui/qgv/QGVSubGraph.cpp:69:56: error: use of undeclared identifier 'TRUE'
            ("cluster_" + _name).toLocal8Bit().data(), TRUE);
                                                       ^
/tmp/gazebo11-20240220-52120-92epuq/gazebo-11.14.0/gazebo/gui/qgv/QGVSubGraph.cpp:72:71: error: use of undeclared identifier 'TRUE'
        sgraph = agsubg(_sgraph->graph(), _name.toLocal8Bit().data(), TRUE);
                                                                      ^
make[2]: *** [gazebo/gui/CMakeFiles/gazebo_gui.dir/qgv/QGVSubGraph.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
~~~

Attempting to reproduce here:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo11-homebrew-amd64&build=198)](https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/198/) https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/198/

I am testing a patch (https://github.com/gazebosim/gazebo-classic/commit/660ae15f4af1f5ea8d9d50d4a24e4d91a94f9c2d) to fix this.

**Comment by scpeters** [comment]
fix in https://github.com/gazebosim/gazebo-classic/pull/3373

**Comment by traversaro** [comment]
I confess that is nice for me when a new dependency first hit homebrew, so I get the fix for free when the same dependency gets updated on conda-forge. : )

**Comment by scpeters** [comment]
> I confess that is nice for me when a new dependency first hit homebrew, so I get the fix for free when the same dependency gets updated on conda-forge. : )

happy to be of service :)
