### ISSUE TITLE
Loading .dll plugin on Windows problem

### ISSUE THREAD

**Issue by WillyTuring** [osrf/gazebo#3392]
Does anyone have any experience on loading the .dll plugin on Windows?

The problem i am encountering now is that the "this->node->Init();" the node could be initiated but when we call Advertise() method trying to public a topic, the program hangs there.

**Comment by traversaro** [comment]
> Does anyone have any experience on loading the .dll plugin on Windows?

Which `.dll plugin` ?

**Comment by WillyTuring** [comment]
![image](https://github.com/user-attachments/assets/ae4c124f-059b-46bf-80e0-535261b321a1)
Here in my world.world file, i am loading a GUI plugin.

Here is the initial part of the code:
![image](https://github.com/user-attachments/assets/8296882b-b916-4656-b640-50b1f7961085)

The Node init succeed, but we hand in calling Advertise() method, here is the verbose printout:
![image](https://github.com/user-attachments/assets/e217eb50-4941-48e2-8431-74a31926e9bb)

**Comment by WillyTuring** [comment]
![image](https://github.com/user-attachments/assets/0f7c2fa4-27c5-4a89-ad74-ecfbf812be22)
Hi any idea about this problem?

> > Does anyone have any experience on loading the .dll plugin on Windows?
> 
> Which `.dll plugin` ?


I have read the comment on this issue ""File already exists in database: vector3d.proto" when World::Load is called #3225 ; but didn't quite understand how to apply it.

**Comment by traversaro** [comment]
Are you sure you are not compiling some library as static somewhere? That error is related to a proto being added to times to the internal protobuf database.

**Comment by WillyTuring** [comment]
I am using the custom message proto for exchange data among the plugins(GUI plugin, model plugin as well as the visual plugin); i compile them as STATIC library and link it as such:
![image](https://github.com/user-attachments/assets/bd7c2000-7d23-4b15-8f3a-8308f89fbbef)

What is the issue with that?

**Comment by WillyTuring** [comment]
> I am using the custom message proto for exchange data among the plugins(GUI plugin, model plugin as well as the visual plugin); i compile them as STATIC library and link it as such: ![image](https://private-user-images.githubusercontent.com/33994287/357314947-bd7c2000-7d23-4b15-8f3a-8308f89fbbef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ0NDMsIm5iZiI6MTcyMzUzNDE0MywicGF0aCI6Ii8zMzk5NDI4Ny8zNTczMTQ5NDctYmQ3YzIwMDAtN2QyMy00YjE1LThmM2EtODMwOGY4OWZiYmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MjkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNzc1ZGM1ZDI0ZGU4ZGI3MWVhNDRjYzc1Y2ZlNTg3ZTRiM2FhY2QzNmZkNzUyN2FjNWMwZWM3M2YzZGRiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.va0FZDehDHAe1zAdKNV2cc9YhbNbNCz5jtkZrkjTueE)
> 
> What is the issue with that?

I could build it as SHARED library, but it didn't change the result.

**Comment by WillyTuring** [comment]
Why is it that when trying to build a SHARED library like below:
![image](https://github.com/user-attachments/assets/38c491d7-45b4-43da-ab4b-790f3b224b1c)
only .dll file is being generated, but no .lib file?

**Comment by traversaro** [comment]
> Why is it that when trying to build a SHARED library like below:
> ![image](https://github.com/user-attachments/assets/38c491d7-45b4-43da-ab4b-790f3b224b1c)
> only .dll file is being generated, but no .lib file?

Probably you are not exporting any symbol, either with dllexport decorators or via CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.

**Comment by WillyTuring** [comment]
when i use "set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)" to force it out, the library it generates being linked by other plugins will crash the gazebo, meaning that once launching gazebo, after a while, it will exit.

Will dllexport decorator give us different result? Btw since we are grouping several custom .proto message to one library trying to solve the error of "File already exists in database", i am not sure if the dllexport can still work.

**Comment by traversaro** [comment]
> Will dllexport decorator give us different result?

I guess it depends on the nature of the crash, it is difficult to answer in general.

**Comment by WillyTuring** [comment]
> > Will dllexport decorator give us different result?
> 
> I guess it depends on the nature of the crash, it is difficult to answer in general.

No error being reported whatsoever, the gazebo application just exit out.

**Comment by traversaro** [comment]
> > > Will dllexport decorator give us different result?
> > 
> > 
> > I guess it depends on the nature of the crash, it is difficult to answer in general.
> 
> No error being reported whatsoever, the gazebo application just exit out.

Even if that case, the answer depends on why it crashed. Even if you do not have any error, you can investigate the nature of the crash by attaching a debugger to the process and obtaining a backtrace.

**Comment by WillyTuring** [comment]
> > Will dllexport decorator give us different result?
> 
> I guess it depends on the nature of the crash, it is difficult to answer in general.

I am using gdb tool to run the executable, all i got is "[Thread 26224.0x2480 exited with code 0]" when the gazebo crashed.

**Comment by WillyTuring** [comment]
> > > > Will dllexport decorator give us different result?
> > > 
> > > 
> > > I guess it depends on the nature of the crash, it is difficult to answer in general.
> > 
> > 
> > No error being reported whatsoever, the gazebo application just exit out.
> 
> Even if that case, the answer depends on why it crashed. Even if you do not have any error, you can investigate the nature of the crash by attaching a debugger to the process and obtaining a backtrace.

So here is the debug output:
1.GUI plugin: Loading up GUI plugin
[Thread 5304.0xb24 exited with code 0]
[New Thread 5304.0x34bc]
![image](https://github.com/user-attachments/assets/b2112037-9c61-429b-9a34-30d25fed00ba)

**Comment by traversaro** [comment]
It does not seems something related to shared symbols.
