### ISSUE TITLE
gazebo::init() not called before SDF parser in gzfactory

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#817]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/817)) by Paul Mathieu (Bitbucket: [po1](https://bitbucket.org/%7Bc5c34c75-e3ca-495f-a49a-623b1e159fca%7D/)).**

----------------------------------------
Issue #769 mentions this problem, and it was solved in gzserver but not in gzfactory.

Here is the message that we get when spawning a model using gzfactory in gazebo 1.9:

```
Error [SDF.cc:118] Tried to use callback in sdf::findFile(), but the callback is empty. Did you call sdf::setFindCallback()?
```

Some other tools might be affected too.

**Comment by usmanNoor5** [comment]
> **Original comment by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**
> 
> * changed state from "new" to "resolved"
> 
> [pull request #678](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/678)

where to change
