### ISSUE TITLE
Setting position on heightmap creates offset between collision and visual

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#868]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/868)) by Carlos Agüero (Bitbucket: [caguero](https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/), GitHub: [caguero](https://github.com/caguero)).**

----------------------------------------
[Copyed from [answers.gazebosim.org](http://answers.gazebosim.org/question/4555/setting-position-on-heightmap-creates-offset/)]

When I set a position in my sdf for my heightmap I get an offset between collision and visual for the map as shown in the snapshot below. If I move the objects around I can see that the collision of the map has an offset. I'm able to move the objects into the mountains etc. All objects are affected by this not only the ones in the example snapshot. When I set the y position in the collision and visual to 0 the offset is gone. This error is a new behaviour that wasn't there 2 month ago(I haven't changed anything on the sdf files since july) so this is probably a bug... I'm not sure when this behaviour first occured because I haven't worked with an heightmap for quite a while...

I'm working with ubuntu precise and gazebo 1.9.1 from the osrf repository(not from source)

Snapshot of the BUG:
![](http://gsyc.es/~caguero/heightmap_offset.png)

Here is the SDF for the heightmap:

```
#!c++

<?xml version='1.0'?>
<sdf version='1.4'>
<model name="my_map">
  <static>true</static>
  <link name="link">
    <collision name="collision">
      <geometry>
        <heightmap>
          <uri>file://path/to/image/terrain.png</uri>
          <size>1500 1500 450</size>
          <pos>0 -35 -71</pos>
        </heightmap>
      </geometry>
    </collision>
    <visual name="visual">
      <geometry>
        <heightmap>
          <texture>
            <diffuse>file://path/to/image/GrassFrozen.png</diffuse>
            <normal>file://path/to/image/flat_normal.png</normal>
            <size>50</size>
          </texture>
          <texture>
            <diffuse>file://path/to/image/Snow.png</diffuse>
            <normal>file://path/to/image/flat_normal.png</normal>
            <size>20</size>
          </texture>
          <texture>
            <diffuse>file://path/to/image/RockRough.png</diffuse>
            <normal>file://path/to/image/flat_normal.png</normal>
            <size>80</size>
          </texture>
          <blend>
            <min_height>-100</min_height>
            <fade_dist>5</fade_dist>
          </blend>
          <blend>
            <min_height>-50</min_height>
            <fade_dist>5</fade_dist>
          </blend>
          <uri>file://path/to/image/terrain.png</uri>
          <size>1500 1500 450</size>
          <pos>0 -35 -71</pos>
        </heightmap>
      </geometry>
    </visual>
  </link>
</model>

</sdf>
```

**Comment by Darkproduct** [comment]
I have the exact same problem on Gazebo 11.3.0. Changing the heightmap position to 0,0 fixes the missmatch between the collision and the visual mesh. This is hard to debug, because the heightmap's collision mesh is not visible even when enabeling collision visualization in the menu.

Can we reopen this issue, so this can be resolved?

@nkoenig

```
Gazebo multi-robot simulator, version 11.3.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
```
